# Generated by Django 4.0.6 on 2022-08-08 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_events_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='data',
        ),
    ]
