# Generated by Django 4.0.6 on 2022-08-12 06:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_userreservation_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreservation',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone in format xxx xxx xxxx', regex='^((\\d{3}[- .]?){2}\\d{4}$)')]),
        ),
    ]
