# Generated by Django 4.0.6 on 2022-08-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_userreservation_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=500)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-is_processed',),
            },
        ),
    ]
